[profile.default]
solc = "0.8.13"
src = "src"
out = "out"
libs = ["lib"]

# RPC endpoints
[rpc_endpoints]
kaia_testnet = "https://public-en.kairos.node.kaia.io"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
