[profile.default]
solc = "0.8.10"
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 1000000

# RPC endpoints
[rpc_endpoints]
kaia_testnet = "https://public-en.kairos.node.kaia.io"
kaia_mainnet = "https://public-en.node.kaia.io"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
